/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllSectionsGraph: typeof import('./components/system/AllSectionsGraph.vue')['default']
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    DataTable: typeof import('./components/admin/DataTable.vue')['default']
    InnerNavBar: typeof import('./components/common/InnerNavBar.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    NavBar: typeof import('./components/common/NavBar.vue')['default']
    Overview: typeof import('./components/system/Overview.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    Review: typeof import('./components/system/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDown: typeof import('./components/common/ScrollDown.vue')['default']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    SectionAi: typeof import('./components/system/SectionAi.vue')['default']
    SectionList: typeof import('./components/system/SectionList.vue')['default']
    SectionReview: typeof import('./components/system/SectionReview.vue')['default']
    SidebarMenu: typeof import('./components/common/SidebarMenu.vue')['default']
    SidebarMenuHome: typeof import('./components/common/SidebarMenuHome.vue')['default']
    StudentsStanding: typeof import('./components/system/StudentsStanding.vue')['default']
    SubjectsTable: typeof import('./components/admin/SubjectsTable.vue')['default']
    TeacherBot: typeof import('./components/common/TeacherBot.vue')['default']
    WelcomeToDashboard: typeof import('./components/system/WelcomeToDashboard.vue')['default']
  }
}
