/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/Admin': RouteRecordInfo<'/admin/Admin', '/admin/Admin', Record<never, never>, Record<never, never>>,
    '/admin/AdminProfiles': RouteRecordInfo<'/admin/AdminProfiles', '/admin/AdminProfiles', Record<never, never>, Record<never, never>>,
    '/admin/TeachersPage': RouteRecordInfo<'/admin/TeachersPage', '/admin/TeachersPage', Record<never, never>, Record<never, never>>,
    '/home/DataEntry': RouteRecordInfo<'/home/DataEntry', '/home/DataEntry', Record<never, never>, Record<never, never>>,
    '/home/dialogs/NewRecordsDialog': RouteRecordInfo<'/home/dialogs/NewRecordsDialog', '/home/dialogs/NewRecordsDialog', Record<never, never>, Record<never, never>>,
    '/home/Home': RouteRecordInfo<'/home/Home', '/home/Home', Record<never, never>, Record<never, never>>,
    '/home/NewRecords': RouteRecordInfo<'/home/NewRecords', '/home/NewRecords', Record<never, never>, Record<never, never>>,
    '/home/Profiles': RouteRecordInfo<'/home/Profiles', '/home/Profiles', Record<never, never>, Record<never, never>>,
    '/home/RecentRecords': RouteRecordInfo<'/home/RecentRecords', '/home/RecentRecords', Record<never, never>, Record<never, never>>,
    '/home/SectionTracking': RouteRecordInfo<'/home/SectionTracking', '/home/SectionTracking', Record<never, never>, Record<never, never>>,
    '/home/Tracking': RouteRecordInfo<'/home/Tracking', '/home/Tracking', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/Welcome': RouteRecordInfo<'/Welcome', '/Welcome', Record<never, never>, Record<never, never>>,
  }
}
